### ISSUE TITLE
xWindowsUpdateAgent.updateNow=$true fails silently

### ISSUE THREAD

**Issue by iamGavinJ** [PowerShell/xWindowsUpdate#59]
I have copied the example from README.md for updateNow and it does not work.  When I log into the VM and check windows update, the last checked time is 'never' and no updates have been appllied.  The only modification to the example is that I have removed the notifications parameter.

    xWindowsUpdateAgent MuSecurityImportant
    {
        IsSingleInstance = 'Yes'
        UpdateNow        = $true
        Category         = @('Security','Important')
        Source           = 'MicrosoftUpdate'
    }

**Comment by ChrisLGardner** [comment]
Testing on a VM for me using the same config as you have there and it patches itself fine, update history shows the updates it installed with the correct date but the Windows Update screen still shows last checked  and updates were installed as "never". I'm wondering if this is due to how the updates are being installed (using a Microsoft.Update.Session comobject) and this is causing the UI to not update in the same way.

**Comment by iamGavinJ** [comment]
Hi @ChrisLGardner I've just managed to get back onto this and I can no longer repro the issue.  There must have been some anomaly with the VM I was testing on, but I've just built 10 VMs via ARM template and DSC extension and all 10 applied windows updates just fine.  Unfortunately I've destroyed the other VM so am not able to do any further testing on it.  Thanks for taking the time to look into it though.

**Comment by william-gross** [comment]
@ChrisLGardner I am experiencing the issue that @iamGavinJ initially described. I have created several VMs via Azure ARM templates and none of them are updating. I'm using the latest Windows Server 2016 Datacenter image, and at the moment the update that is not getting applied is "Definition Update for Windows Defender - KB2267602 (Definition 1.251.377.0)". Please let me know what additional information you need from me in order to repro this.

**Comment by johlju** [comment]
If someone encounters this again it would be good to debug what is happening (or not happening, but should happen). Labeling this as need more information.

**Comment by william-gross** [comment]
@johlju I've noticed that certain updates that appear in the Windows Update UI do not get installed by xWindowsUpdateAgent until days or weeks later. This seems to happen often with the Cumulative Updates (e.g. 2018-04 Cumulative Update). It seems that, eventually, all updates get installed.

Does anyone know why this would happen?

**Comment by johlju** [comment]
@william-gross so maybe that is the issue above too, they would have been installed eventually, but should have been install much sooner? 🤔 I haven't used this resource anything so it's hard for me to see any reason for it doing so. Hopefully someone else has the same problem so we can narrow it down.

**Comment by johlju** [comment]
@william-gross for reference,how does the configuration look like on the server where this is happening?

**Comment by william-gross** [comment]
@johlju The servers where this happens are all Windows Server 2016, currently version 10.0.14393 Build 14393. And here's the DSC block:

        xWindowsUpdateAgent WindowsUpdate {
            IsSingleInstance = 'Yes'
            Source = 'MicrosoftUpdate'
            Category = 'Security', 'Important'
            UpdateNow = $true
        }

Please let me know if there is other info you'd like to see.
