### ISSUE TITLE
Support for installing .msp office patches

### ISSUE THREAD

**Issue by enel1221** [PowerShell/xWindowsUpdate#87]
Allow the DSC module to install .msp office patches with the msiexec /update option. As well as check registry keys for office updates since get-hotfix doesn't display those patches.

**Comment by johlju** [comment]
I think that is out of scope for this module since it focuses on Windows updates. Suggest this is tracked by this issue https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/303. If the community want a dedicated module for Office-product related this then please reach out on the Slack #DSC channel to discuss it; https://dsccommunity.org/community/contact/

Closing this issue at this time.
